version: '2'
services:
  web:
    image: 'microblogpub:latest'
    ports:
     - "127.0.0.1:${WEB_PORT}:5005"
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "./static:/app/static"
    environment:
     - MICROBLOGPUB_MONGODB_HOST=mongo:27017
     - MICROBLOGPUB_INTERNAL_HOST=http://${COMPOSE_PROJECT_NAME}_web_1:5005
     - MICROBLOGPUB_POUSSETACHES_HOST=http://${COMPOSE_PROJECT_NAME}_poussetaches_1:7991
     - POUSSETACHES_AUTH_KEY=${POUSSETACHES_AUTH_KEY}
     - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
  mongo:
    image: "mongo:3"
    volumes:
     - "${DATA_DIR}/mongodb:/data/db"
  poussetaches:
    image: "poussetaches/poussetaches:latest"
    volumes:
     - "${DATA_DIR}/poussetaches:/app/poussetaches_data"
    environment:
     - POUSSETACHES_AUTH_KEY=${POUSSETACHES_AUTH_KEY}
#    ports:
# - "127.0.0.1:${POUSSETACHES_PORT}:7991"
